// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsNlyWqPEesU4FR4AMYXw4E__yHcBwuHY',
    appId: '1:832022392071:web:2b6fb6f8650619a24da9a2',
    messagingSenderId: '832022392071',
    projectId: 'bosai-app-f3cd1',
    authDomain: 'bosai-app-f3cd1.firebaseapp.com',
    storageBucket: 'bosai-app-f3cd1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgy_sqG9dlwBhWWweMGpRK_wlomwGwn64',
    appId: '1:832022392071:android:b31dd2e6a78e86614da9a2',
    messagingSenderId: '832022392071',
    projectId: 'bosai-app-f3cd1',
    storageBucket: 'bosai-app-f3cd1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQFNJV4dIKUBb-cZ4rapHhGYjjgKUMPk4',
    appId: '1:832022392071:ios:e79d495f7ac24f064da9a2',
    messagingSenderId: '832022392071',
    projectId: 'bosai-app-f3cd1',
    storageBucket: 'bosai-app-f3cd1.firebasestorage.app',
    iosBundleId: 'com.example.myWebApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQFNJV4dIKUBb-cZ4rapHhGYjjgKUMPk4',
    appId: '1:832022392071:ios:e79d495f7ac24f064da9a2',
    messagingSenderId: '832022392071',
    projectId: 'bosai-app-f3cd1',
    storageBucket: 'bosai-app-f3cd1.firebasestorage.app',
    iosBundleId: 'com.example.myWebApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCsNlyWqPEesU4FR4AMYXw4E__yHcBwuHY',
    appId: '1:832022392071:web:2b6fb6f8650619a24da9a2',
    messagingSenderId: '832022392071',
    projectId: 'bosai-app-f3cd1',
    authDomain: 'bosai-app-f3cd1.firebaseapp.com',
    storageBucket: 'bosai-app-f3cd1.firebasestorage.app',
  );
}
